-- Create sequence auth
CREATE SEQUENCE AUTH_SEQ
MINVALUE 1
NOMAXVALUE
START WITH 1
INCREMENT BY 1
CACHE 10;

-- Create sequence product
CREATE SEQUENCE PRODUCT_SEQ
MINVALUE 1
NOMAXVALUE
START WITH 1
INCREMENT BY 1
CACHE 10;

-- Create sequence cart
CREATE SEQUENCE CART_SEQ
MINVALUE 1
NOMAXVALUE
START WITH 1
INCREMENT BY 1
CACHE 10;

-- Create sequence cart item
CREATE SEQUENCE CART_ITEM_SEQ
MINVALUE 1
NOMAXVALUE
START WITH 1
INCREMENT BY 1
CACHE 10;

-- Create sequence order
CREATE SEQUENCE ORDER_SEQ
MINVALUE 1000
NOMAXVALUE
START WITH 1000
INCREMENT BY 1
CACHE 10;

-- Create sequence order items
CREATE SEQUENCE ORDER_ITEMS_SEQ
MINVALUE 1
NOMAXVALUE
START WITH 1
INCREMENT BY 1
CACHE 10;

-- Create sequence Payments
CREATE SEQUENCE PAYMENTS_SEQ
MINVALUE 1
NOMAXVALUE
START WITH 1
INCREMENT BY 1
CACHE 10;

-- Create sequence shipping
CREATE SEQUENCE SHIPPING_SEQ
MINVALUE 1
NOMAXVALUE
START WITH 1
INCREMENT BY 1
CACHE 10;

-- Create sequence wishlist
CREATE SEQUENCE WISHLISTS_SEQ
MINVALUE 1
NOMAXVALUE
START WITH 1
INCREMENT BY 1
CACHE 10;

-- Create sequence wishlist items
CREATE SEQUENCE WISHLIST_ITEM_SEQ
MINVALUE 1
NOMAXVALUE
START WITH 1
INCREMENT BY 1
CACHE 10;

-- Customers Table
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER DEFAULT AUTH_SEQ.NEXTVAL PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    EMAIL VARCHAR2(100),
    PASSWORD VARCHAR2(100),
    CONSTRAINT chk_uq_email UNIQUE (EMAIL)
);

-- Products Table
CREATE TABLE PRODUCTS (
    PRODUCT_ID NUMBER DEFAULT PRODUCT_SEQ.NEXTVAL PRIMARY KEY,
    NAME VARCHAR2(100),
    PRICE NUMBER,
    STOCK_QUANTITY NUMBER,
    DESCRIPTION VARCHAR2(500),
    CATEGORY VARCHAR2(30),
    IMAGE VARCHAR2(50)
);

-- Shopping Carts Table
CREATE TABLE SHOPPING_CART (
    CART_ID NUMBER DEFAULT CART_SEQ.NEXTVAL PRIMARY KEY,
    CUSTOMER_ID NUMBER REFERENCES CUSTOMERS(CUSTOMER_ID)
);

-- Cart Items Table
CREATE TABLE CART_ITEMS (
    CART_ITEM_ID NUMBER DEFAULT CART_ITEM_SEQ.NEXTVAL PRIMARY KEY,
    CART_ID NUMBER REFERENCES SHOPPING_CART(CART_ID),
    PRODUCT_ID NUMBER REFERENCES PRODUCTS(PRODUCT_ID),
    QUANTITY NUMBER
);

-- Wish Lists Table
CREATE TABLE WISHLISTS (
    WISHLIST_ID NUMBER DEFAULT WISHLISTS_SEQ.NEXTVAL PRIMARY KEY,
    CUSTOMER_ID NUMBER REFERENCES CUSTOMERS(CUSTOMER_ID)
);

-- Wishlist Items Table
CREATE TABLE WISHLISTS_ITEMS (
    WISHLIST_ITEM_ID NUMBER DEFAULT WISHLIST_ITEM_SEQ.NEXTVAL PRIMARY KEY,
    WISHLIST_ID NUMBER REFERENCES WISHLISTS(WISHLIST_ID),
    PRODUCT_ID NUMBER REFERENCES PRODUCTS(PRODUCT_ID)
);

-- Orders Table
CREATE TABLE ORDERS (
    ORDER_ID NUMBER DEFAULT ORDER_SEQ.NEXTVAL PRIMARY KEY,
    CUSTOMER_ID NUMBER REFERENCES CUSTOMERS(CUSTOMER_ID),
    ORDER_DATE DATE,
    STATUS VARCHAR2(50),
    TOTAL_AMOUNT NUMBER
);

-- Order Items Table
CREATE TABLE ORDER_ITEMS (
    ORDER_ITEM_ID NUMBER DEFAULT ORDER_ITEMS_SEQ.NEXTVAL PRIMARY KEY,
    ORDER_ID NUMBER REFERENCES ORDERS(ORDER_ID),
    PRODUCT_ID NUMBER REFERENCES PRODUCTS(PRODUCT_ID),
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER
);

-- Payments Table
CREATE TABLE PAYMENTS (
    PAYMENT_ID NUMBER DEFAULT PAYMENTS_SEQ.NEXTVAL PRIMARY KEY,
    ORDER_ID NUMBER REFERENCES ORDERS(ORDER_ID),
    PAYMENT_DATE DATE,
    AMOUNT NUMBER,
    PAYMENT_METHOD VARCHAR2(50)
);

-- Shipping Information Table
CREATE TABLE SHIPPING_INFORMATION (
    SHIPPING_ID NUMBER DEFAULT SHIPPING_SEQ.NEXTVAL PRIMARY KEY,
    ORDER_ID NUMBER REFERENCES ORDERS(ORDER_ID),
    ADDRESS VARCHAR2(200),
    CITY VARCHAR2(100),
    COUNTRY VARCHAR2(100),
    SHIPPING_DATE DATE
);
