SET ECHO ON;

INSERT INTO PRODUCTS (NAME, PRICE, STOCK_QUANTITY, DESCRIPTION, CATEGORY, IMAGE) VALUES ('HP Laptop', 34700, 8, 'Boost your productivity with our high-performance laptop. Powerful specs for efficiency. Sleek design, perfect for work or entertainment.', 'Electronics', 'hp.jpg');
INSERT INTO PRODUCTS (NAME, PRICE, STOCK_QUANTITY, DESCRIPTION, CATEGORY, IMAGE) VALUES ('Men''s Leather Jacket', 2199, 100, 'Stylish leather jacket for men. Elevate your style with our men''s leather jacket. Stylish and durable. A timeless addition to your wardrobe.', 'Clothing', 'mlj.jpg');
INSERT INTO PRODUCTS (NAME, PRICE, STOCK_QUANTITY, DESCRIPTION, CATEGORY, IMAGE) VALUES ('Modern Desk', 3372, 40, 'Create a stylish workspace with our modern desk. Sleek design for a contemporary look. Perfect for your home office or study area.', 'Furniture', 'modern-desk.jpg');
INSERT INTO PRODUCTS (NAME, PRICE, STOCK_QUANTITY, DESCRIPTION, CATEGORY, IMAGE) VALUES ('Himalaya Neem Face Wash', 242, 80, 'An easiest way to get rid of the dust particles. Refresh your skin with our gentle face wash. Cleanses and revitalizes. Leaves your skin feeling fresh and rejuvenated.', 'Beauty Care', 'himalaya-facewash.jpg');
INSERT INTO PRODUCTS (NAME, PRICE, STOCK_QUANTITY, DESCRIPTION, CATEGORY, IMAGE) VALUES ('Philips Coffee Maker', 2644, 30, 'Start your day right with our automatic coffee maker. Programmable features for convenience. Brew your favorite coffee at the touch of a button.', 'Home Appliances', 'coffee-maker.jpg');
INSERT INTO PRODUCTS (NAME, PRICE, STOCK_QUANTITY, DESCRIPTION, CATEGORY, IMAGE) VALUES ('Lymio Hoodies', 599, 30, 'Stay warm and stylish with our cozy hoodie. Crafted from soft, high-quality fabric, this hoodie is perfect for chilly days and casual outings.', 'Clothing', 'hoodie.jpg');
INSERT INTO PRODUCTS (NAME, PRICE, STOCK_QUANTITY, DESCRIPTION, CATEGORY, IMAGE) VALUES ('Fastrack Analog Watch', 765, 12, 'Embrace timeless elegance with our sophisticated watch. Featuring a precision-engineered movement and a stylish design, this watch is the perfect accessory for any occasion.', 'Electronics', 'watch.jpg');
INSERT INTO PRODUCTS (NAME, PRICE, STOCK_QUANTITY, DESCRIPTION, CATEGORY, IMAGE) VALUES ('Round Neck T-Shirt', 319, 10, 'Elevate your wardrobe with our classic t-shirt. Made from breathable cotton, it''s comfortable for everyday wear. Versatile and timeless, it''s a wardrobe essential.', 'Clothing', 't-shirt.jpg');
INSERT INTO PRODUCTS (NAME, PRICE, STOCK_QUANTITY, DESCRIPTION, CATEGORY, IMAGE) VALUES ('Samsung Galaxy Tab A7 Lite', 10999, 26, 'Unleash productivity with our cutting-edge tablet. High-resolution display for clarity. Slim and portable, your on-the-go companion.', 'Electronics', 'tablet.jpg');
INSERT INTO PRODUCTS (NAME, PRICE, STOCK_QUANTITY, DESCRIPTION, CATEGORY, IMAGE) VALUES ('Wakefit Sofa Set for Living Room', 10097, 16, 'Experience comfort and relaxation with our plush sofa. Soft cushions for ultimate coziness. Stylish design that enhances the decor of your living space. The perfect centerpiece for lounging. Create a cozy haven at home with our inviting and comfortable sofa.', 'Furniture', 'sofa.jpg');
INSERT INTO PRODUCTS (NAME, PRICE, STOCK_QUANTITY, DESCRIPTION, CATEGORY, IMAGE) VALUES ('Butterfly Jet Elite Mixer', 3299, 30, 'Revolutionize your kitchen with our powerful mixie. Versatile appliance for blending and grinding. Durable and efficient, simplifying your cooking experience.', 'Home Appliances', 'mixie.jpg');
INSERT INTO PRODUCTS (NAME, PRICE, STOCK_QUANTITY, DESCRIPTION, CATEGORY, IMAGE) VALUES ('FOGG Fragrance Body Spray for Men', 412, 20, 'Embrace a burst of freshness with our invigorating body spray. Long-lasting fragrance that keeps you feeling confident throughout the day. A quick and easy way to add a touch of fragrance to your daily routine.', 'Beauty Care', 'body-spray.jpg');
